server:
  port: 9312
spring:
  application:
    name: spring-boot-admin-client2
  boot:
    admin:
      client:
        url: http://localhost:9310
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
